# Generated by Django 6.0.2 on 2026-02-17 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('short_description', models.CharField(max_length=180)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField()),
                ('hero_image_light', models.ImageField(blank=True, null=True, upload_to='case-studies/hero/')),
                ('hero_image_dark', models.ImageField(blank=True, null=True, upload_to='case-studies/hero/')),
                ('repo_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('role', models.CharField(max_length=120)),
                ('stack', models.CharField(max_length=160)),
                ('timeline', models.CharField(max_length=120)),
                ('problem', models.TextField()),
                ('goals', models.TextField(help_text='Store as one bullet per line')),
                ('process_discover', models.TextField()),
                ('process_design', models.TextField()),
                ('process_build', models.TextField()),
                ('process_refine_launch', models.TextField()),
                ('solution_intro', models.TextField()),
                ('solution_1_title', models.CharField(max_length=120)),
                ('solution_1_body', models.TextField()),
                ('solution_1_image_light', models.ImageField(blank=True, null=True, upload_to='case-studies/solutions/')),
                ('solution_1_image_dark', models.ImageField(blank=True, null=True, upload_to='case-studies/solutions/')),
                ('solution_2_title', models.CharField(max_length=120)),
                ('solution_2_body', models.TextField()),
                ('solution_2_image_light', models.ImageField(blank=True, null=True, upload_to='case-studies/solutions/')),
                ('solution_2_image_dark', models.ImageField(blank=True, null=True, upload_to='case-studies/solutions/')),
                ('solution_3_title', models.CharField(max_length=120)),
                ('solution_3_body', models.TextField()),
                ('solution_3_image_light', models.ImageField(blank=True, null=True, upload_to='case-studies/solutions/')),
                ('solution_3_image_dark', models.ImageField(blank=True, null=True, upload_to='case-studies/solutions/')),
                ('outcome_intro', models.TextField()),
                ('outcome_bullets', models.TextField(help_text='Store as one bullet per line')),
                ('reflection_intro', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_study', to='portfolio.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='portfolio.tag'),
        ),
    ]
