# Generated by Django 6.0.2 on 2026-02-17 11:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='reflection_body',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
