# Generated by Django 6.0.2 on 2026-02-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_casestudy_reflection_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail_dark',
            field=models.ImageField(blank=True, null=True, upload_to='projects/thumbnails/'),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail_light',
            field=models.ImageField(blank=True, null=True, upload_to='projects/thumbnails/'),
        ),
    ]
