# Generated by Django 6.0.2 on 2026-02-17 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_thumbnail_dark_project_thumbnail_light'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='thumbnail_dark',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='project',
            name='thumbnail_light',
        ),
    ]
