# Generated by Django 6.0.2 on 2026-07-29 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_thumbnail_dark_project_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='use_structured_sections',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='CaseStudySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('problem', 'Problem'), ('users_and_goals', 'Users and goals'), ('constraints', 'Constraints'), ('role', 'Role and responsibilities'), ('research_and_planning', 'Research and planning'), ('solution', 'Solution'), ('technical_decisions', 'Technical decisions'), ('challenges_and_tradeoffs', 'Challenges and trade-offs'), ('testing', 'Testing'), ('accessibility', 'Accessibility'), ('results', 'Results'), ('lessons_learned', 'Lessons learned'), ('improvements', 'What I would improve next'), ('development_process', 'Development process')], max_length=40)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='portfolio.casestudy')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='case-studies/sections/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('product', 'Product'), ('mobile', 'Mobile'), ('desktop', 'Desktop'), ('process', 'Process'), ('diagram', 'Diagram'), ('testing_evidence', 'Testing evidence'), ('before', 'Before'), ('after', 'After')], max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='portfolio.casestudysection')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
